id: P8A48C8B4
initial_creation_type: input
source_metadata:
  title: Tulku Zangpo Drakpa
  language: de
  description: 'Texts revealed by the 14th-century tertön Zangpo Drakpa (bzang po
    grags pa):'
  volume:
    09e1c4cf297e410c8e6e1c0cff08a2ab:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    6565c6fe1ac44590a67e005d73f78756:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    0bb9a86335e347f0b6903a327b417d79:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    ee96ae5991cc40b590f74a6b57a717f3:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    e41bff37e42b4ea0a8310a3690c53fcc:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    05d884038a994fcfa61c52f128531419:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    ea59ae34cfd546d1822080c3e3693a2d:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    8bc0924cbe0c4dd8bba7d087ab04fdd0:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
created_at: '2022-03-01T01:59:25.929941'
last_modified_at: '2022-03-01T01:59:25.929944'
